### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by williamboman** [ChristianKohler/web-presentation#1]
e.g. create a `gh-pages` branch and let GitHub host a live demo (http://christiankohler.github.io/web-presentation), and add link to repo description.

**Comment by vysinsky** [comment]
:+1:

**Comment by ChristianKohler** [comment]
Good idea. I added a gh-pages branch with the demo directory. I'll add a travis ci in the next few days to update the gh-pages automatically.

Also, the demo is very basic at the moment. If you have ideas on what we could display on the demo slides please let me know or make a pull request. Thank you.
